### ISSUE TITLE
Unity 5.2 iOS building with missing frameworks.

### ISSUE THREAD

**Issue by rygo6** [bitstadium/HockeySDK-Unity-iOS#18]
My iOS Xcode project builds with the frameworks missing that HockeyApp needs.

I noticed that the adding of frameworks was removed from your PostProcess script:
https://github.com/bitstadium/HockeySDK-Unity-iOS/commit/0a3f1a31db5037cfc79e2cb8585fd2ae3d1963c9?_pjax=%23js-repo-pjax-container

Are you sure that is correct? Unity 5.2 is not adding in the needed frameworks via any other means that I can discern.

**Comment by rygo6** [comment]
I discovered that none of your native iOS objects had any of the frameworks checked in the 'Framework Dependencies' section. 

Either they were exported without these checked, or some issue in Unity makes this data not be retained through the process of exporting a package.

**Comment by chrwend** [comment]
Hi,

since Unity 5 we don't need the post build script to copy all the required frameworks anymore. Just select the `libHockeyAppUnity.a` file inside the *Assets/HockeyAppUnityIOS* directory and check the frameworks in the *Inspector* panel:

* AssetsLibrary
* CoreText
* MobileCoreServices
* QuickLook
* Security

Just open the *ExampleGame* project as a reference. Let me know if there are any further issues.

Thank you,

Chris
