### ISSUE TITLE
Bitcode Support

### ISSUE THREAD

**Issue by alexpwer** [bitstadium/HockeySDK-Unity-iOS#21]
SDK doesn't support bitcode

Libraries/HockeyAppUnityIOS/libHockeyAppUnity.a(HockeyAppUnity.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lumaxis** [comment]
There is a version preliminary version with Bitcode support in the [feature/bitcode-support](https://github.com/bitstadium/HockeySDK-Unity-iOS/tree/feature/bitcode-support) branch that you can use until we update the release version with that feature.

That said, my suggestion would be to disable Bitcode all together for the time being, since it is not required for iOS apps and also has no known benefits. Note for example that Bitcode is not required to benefit from other App Thinning features like On-Demand Resources or Slicing but makes receiving symbolicated crash reports significantly more tedious.

We have written a bit more about the topic here: http://support.hockeyapp.net/kb/client-integration-ios-mac-os-x/how-to-solve-symbolication-problems#bitcode
